### ISSUE TITLE
Feature : add a cross in the background

### ISSUE THREAD

**Issue by jpvincent** [Evlos/placeholder#1]
Hi
thank you for this code, it helped me generate a light placeholder that does not disturb my demos !
So, thank you for sharing and for having the demo server.

The grey background is good enough for me, however it would be nice to have 2 lines showing the diagonales of the image, for the user to better see the limit of the image, especially if it has to be cropped via CSS.

Is it an addition you plan to make ?

Cheers

**Comment by Evlos** [comment]
Hi,

This feature looks good to me, I will release a new version with it this week.

Regards

**Comment by Evlos** [comment]
```<img src="https://ph.zxc.im/512x128+cross" />```

![](https://ph.zxc.im/512x128+cross)

```<img src="https://ph.zxc.im/512x128+border" />```

![](https://ph.zxc.im/512x128+border)

```<img src="https://ph.zxc.im/512x128+cross+border" />```

![](https://ph.zxc.im/512x128+cross+border)

**Comment by jpvincent** [comment]
Excellent !
thank you so much
